//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ArticleDetailView:public drogon::DrTemplate<ArticleDetailView>
{
public:
	ArticleDetailView(){};
	virtual ~ArticleDetailView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
