//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class BackStage:public drogon::DrTemplate<BackStage>
{
public:
	BackStage(){};
	virtual ~BackStage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
