//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class HomePageView:public drogon::DrTemplate<HomePageView>
{
public:
	HomePageView(){};
	virtual ~HomePageView(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
