/**
 *
 *  RestfulArticlesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulArticlesCtrl.h"
#include <string>


void RestfulArticlesCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Articles::PrimaryKeyType &&id)
{
    RestfulArticlesCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulArticlesCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Articles::PrimaryKeyType &&id)
{
    RestfulArticlesCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulArticlesCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Articles::PrimaryKeyType &&id)
{
    RestfulArticlesCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulArticlesCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulArticlesCtrlBase::get(req, std::move(callback));
}

void RestfulArticlesCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulArticlesCtrlBase::create(req, std::move(callback));
}
